java_test(
    name = "trie_loading_test",
    srcs = ["TestTrieLoading.java"],
    deps = [
        "//src:trie",
        "//src:trie_node",
        "@junit_jar//jar",
        "@hamcrest_jar//jar",
    ],
    visibility = ["//visibility:public"],
)
