java_library(
    name = "trie_node",
    srcs = ["TrieNode.java"],
    visibility = ["//visibility:public"],
)

java_library(
    name = "trie",
    srcs = ["Trie.java"],
    deps = [":trie_node"],
    visibility = ["//visibility:public"],
)
